# Generated by Django 3.0.3 on 2020-03-20 06:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('vmail', models.EmailField(max_length=200)),
                ('vname', models.CharField(max_length=200)),
                ('vid', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)])),
                ('vimage', models.ImageField(upload_to='')),
                ('election', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sevapp.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Poff',
            fields=[
                ('pmail', models.EmailField(max_length=200)),
                ('pname', models.CharField(max_length=200)),
                ('pid', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)])),
                ('pkey', models.CharField(max_length=200)),
                ('election', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sevapp.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('cmail', models.EmailField(max_length=200)),
                ('cname', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('vote_earned', models.PositiveIntegerField(verbose_name='Votes')),
                ('cid', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)])),
                ('cimage', models.ImageField(default='null', upload_to='')),
                ('election', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sevapp.Election')),
            ],
        ),
    ]
