# Generated by Django 3.0.3 on 2020-03-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('Hash_key', models.CharField(max_length=200)),
                ('user', models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='sevapp.Entry')),
            ],
        ),
    ]
