# Generated by Django 3.0.3 on 2020-03-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0005_auto_20200320_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sevapp.Admin')),
            ],
        ),
    ]
