# Generated by Django 3.0.3 on 2020-03-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0010_poff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poff',
        ),
    ]
