# Generated by Django 3.0.3 on 2020-03-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0013_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('Email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('share', models.ImageField(upload_to='shares')),
                ('password', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sevapp.Entry')),
            ],
        ),
    ]
