# Generated by Django 3.0.3 on 2020-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0014_auto_20200321_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='share',
            field=models.ImageField(null=True, upload_to='shares'),
        ),
    ]
