# Generated by Django 3.0.3 on 2020-03-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0015_auto_20200321_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='share',
        ),
    ]
