# Generated by Django 3.0.3 on 2020-03-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0016_remove_voter_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='share',
            field=models.ImageField(null=True, upload_to='shares'),
        ),
    ]
