# Generated by Django 3.0.3 on 2020-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0017_voter_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.BigIntegerField(default=0),
        ),
    ]
