# Generated by Django 3.0.3 on 2020-03-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0018_auto_20200323_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='poff',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sevapp.Election'),
        ),
        migrations.AddField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sevapp.Election'),
        ),
    ]
