# Generated by Django 3.0.3 on 2020-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0019_auto_20200325_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='nota',
            field=models.BigIntegerField(default=0),
        ),
    ]
