# Generated by Django 3.0.3 on 2020-04-20 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevapp', '0020_election_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Aadhaar_Number',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
